// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdqjkgtioakgnxqbyimi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkcWprZ3Rpb2FrZ254cWJ5aW1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MzIzNzksImV4cCI6MjA2OTQwODM3OX0.NLq_UVMEfCy5gwD-DXxTjSaJ4hnCrXlX2q6FtNiVQIU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});